# Welcome to Jekyll!
#

# Site settings
title: Park Lab
description: |
  From integrative metabolomics  
  to understanding human diseases  
  & enhancing CO<sub>2</sub> utilization  
owner: Junyoung O. Park
first_published: 2017 # if migrating another site, the year of your first publish
email: jop@ucla.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jopark.github.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  email: mailto:jop@ucla.edu
  phone: tel:2016613970
  skype: skype:jpark432?call
  google: https://scholar.google.com/citations?user=9qHkdoYAAAAJ&hl=en
  #google-plus-square: https://plus.google.com/u/0/+<username>
  linkedin-square: https://linkedin.com/in/jopark432
  github: https://github.com/jopark
  #facebook-official: https://facebook.com/<username>
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
